# Generated by Django 2.2.3 on 2019-12-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
