# Generated by Django 3.0 on 2019-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='market_id',
            field=models.IntegerField(default=-1),
        ),
    ]
